blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/qb20nh/cbbg/discussions
    about: Ask general on-topic questions and discuss with the community about the mod.
